
keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_URL}
  public-client: false
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_CLIENT_ID}
  bearer-only: true
  ssl-required: external
  use-resource-role-mappings: true
  principal-attribute: preferred_username
  enable-basic-auth: true
  credentials:
    secret: ${KEYCLOAK_AUTH_SECRET}



platform-data-url: ${PLATFORM_DATA_ENDPOINT_URL}
platform-data-token: ${PLATFORM_DATA_TOKEN}

gov:
  notify:
    api:
      key: ${GOV_NOTIFY_CLIENT_ID}
      notification:
        emailTemplateId: ${GOV_NOTIFY_NOTIFICATION_EMAIL_TEMPLATE_ID}
        smsTemplateId:  ${GOV_NOTIFY_NOTIFICATION_SMS_TEMPLATE_ID}

camunda:
  bpm:
    process-engine-name: borders
    database:
      type: ${CAMUNDA_DB_TYPE}
    deployment-resource-pattern:
        - classpath*:**/*.bpmn
        - classpath*:**/*.bpmn20.xml
        - classpath*:**/*.dmn
        - classpath*:**/*.dmn11.xml
        - classpath*:**/*.cmmn
        - classpath*:**/*.cmmn10.xml
        - classpath*:**/*.cmmn11.xml
        - file:///workflow-resources-public/bpmn/**/*.bpmn
        - file:///workflow-resources-public/cmmn/**/*.cmmn
        - file:///workflow-resources-public/dmn/**/*.dmn
spring:
  datasource:
    driver-class-name: ${ENGINE_DB_DRIVER}
    password: ${ENGINE_DB_PASSWORD}
    username: ${ENGINE_DB_USERNAME}
    url: ${ENGINE_DB_URL}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration


